name: build-deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: use node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.5.1'
      - run: | 
          npm install
          npm run build
  deploy:
    environment: droplet
    runs-on: ubuntu-latest
    steps:
      - name: Deploy app
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
          source: '.'
          target: "~/site"




            
          
