name: build-deploy

on:
  push:
    branches: [main]

jobs:
  build:
    environment: droplet
    runs-on: ubuntu-latest
    steps:
      #  - name: checkout repo
      #    uses: actions/checkout@v3
      #  - name: use node.js
      #    uses: actions/setup-node@v3
      #    with:
      #      node-version: '22.5.1'
      #  - run: |
      #      npm install
      #      npm run build
      #  - name: Deploy app
      #    uses: appleboy/scp-action@v0.1.7
      #    with:
      #     host: ${{secrets.SSH_HOST}}
      #      username: ${{secrets.SSH_USERNAME}}
      #      key: ${{secrets.SSH_KEY}}
      #      source: './dist'
      #      target: '~/site'
      - name: checkout repo
        uses: actions/checkout@v3
      - run: |
          mkdir -p ~/.ssh/ && touch ~/.ssh/known_hosts
          ssh-keyscan gamma-squid.xyz >> ~/.ssh/known_hosts
          eval $(ssh-agent)
          ssh-add - <<< "${{secrets.SSH_KEY}}"
          echo 'ssh keys added'

          npm install
          npm run build
          ssh -o "StrictHostKeyChecking no" ${{secrets.SSH_USERNAME}}@${{secrets.SSH_HOST}}
          ls
          scp -r ~/dist ${{secrets.SSH_USERNAME}}@${{secrets.SSH_HOST}}:/site
          echo 'deployment successful'
