name: Build & Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Vue app
        uses: apple/ssh-action@v1.10
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}

          script: |
            mkdir test
            cd test
            git clone git@github.com:cha0jun/gamma.git
            echo 'Deployment successful to droplet'
            npm run build
            rsync -a --delete /gamma/dist /var/www/html
            echo 'Remote build successful in droplet'
          
