name: Build & Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    environment: droplet
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Vue app
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}

          script: |
            cd gamma
            git pull
            echo 'Deployment successful to droplet'
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            npm install
            npm run build
            cp -R /gamma/dist /var/www/html
            echo 'Remote build successful in droplet'
          
