name: build-deploy

on:
  push:
    branches: [main]

jobs:
  build:
    environment: droplet
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo & deploy app
        uses: actions/checkout@v3
      - run: |
          mkdir -p ~/.ssh/ && touch ~/.ssh/known_hosts
          ssh-keyscan gamma-squid.xyz >> ~/.ssh/known_hosts
          eval $(ssh-agent)
          ssh-add - <<< "${{secrets.SSH_SECRET_KEY}}"
          echo 'ssh keys added'

          ssh -o "StrictHostKeyChecking no" ${{secrets.SSH_USERNAME}}@${{secrets.SSH_HOST}}

          npm i
          npm run build
          scp -r ./dist ${{secrets.SSH_USERNAME}}@${{secrets.SSH_HOST}}:~/site
          echo 'build & push successful'

          echo 'start rolling update'
          tmux new-session -d -s "8080" http-server ~/site/dist -p 8080
          tmux new-session -d -s "8081" http-server ~/site/dist -p 8081
          echo 'update successful'
